version: '3.8'

services:
  web:
    build: ./app
    container_name: topp-nfs-web
    restart: always
    command: gunicorn -w 4 -b 0.0.0.0:5000 app:app
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://nfs_user:geheim123@db:5432/nfs_db
      - SECRET_KEY=dein_sehr_geheimer_key_fuer_cookies
      # Mail-Server Config hier eintragen (optional für jetzt)
      # - MAIL_SERVER=smtp.gmail.com
      # - MAIL_USERNAME=...
    depends_on:
      - db
    volumes:
      - ./app/static/uploads:/app/static/uploads

  db:
    image: postgres:15-alpine
    container_name: topp-nfs-db
    restart: always
    environment:
      POSTGRES_USER: nfs_user
      POSTGRES_PASSWORD: geheim123
      POSTGRES_DB: nfs_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
