services:
  web:
    build: ./app
    container_name: topp-nfs-web
    restart: always
    ports:
      - "5000:5000"
    environment:
      # Hier werden die Zugangsdaten für die Datenbank definiert
      - DATABASE_URL=postgresql://nfs_user:geheim123@db:5432/nfs_db
      - SECRET_KEY=dein_sehr_geheimer_produktions_key_hier_aendern
      # Optional: Mail Server Konfiguration
      # - MAIL_SERVER=smtp.example.com
      # - MAIL_USERNAME=user@example.com
      # - MAIL_PASSWORD=pw
    depends_on:
      - db
    volumes:
      # Damit Bilder-Uploads erhalten bleiben, auch wenn der Container neu gebaut wird
      - ./app/static/uploads:/service/app/static/uploads

  db:
    image: postgres:15-alpine
    container_name: topp-nfs-db
    restart: always
    environment:
      POSTGRES_USER: nfs_user
      POSTGRES_PASSWORD: geheim123
      POSTGRES_DB: nfs_db
    volumes:
      # Hier werden die Datenbank-Dateien dauerhaft gespeichert
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
